DELETE FROM USERS_ROLES;
DELETE FROM ROLES;
DELETE FROM USERS;
DELETE FROM GENRES;
DELETE FROM BOOKS;

INSERT INTO GENRES (NAME) VALUES ('Povest');
INSERT INTO GENRES (NAME) VALUES ('Skazka');

INSERT INTO BOOKS (NAME, AUTHOR, GENRE_ID) VALUES ('Book1Name', 'Pushkin', 1);
INSERT INTO BOOKS (NAME, AUTHOR,  GENRE_ID) VALUES ('Book2Name', 'Lermontov', 2);
INSERT INTO BOOKS (NAME, AUTHOR, GENRE_ID) VALUES ('Book3Name', 'Gogol', 1);

INSERT INTO USERS (NAME , SURNAME, USER_NAME, PASSWORD) VALUES ('Иван', 'Иванов', 'ivanov', '$2a$04$j6PFY6JpFTwSX7bpBQu9ouHUeSXIdkgCXsXCKrFwd/fzKm.wVyhI.');
INSERT INTO USERS (NAME , SURNAME, USER_NAME, PASSWORD) VALUES ('Пётр', 'Петров', 'petrov', '$2a$04$j6PFY6JpFTwSX7bpBQu9ouHUeSXIdkgCXsXCKrFwd/fzKm.wVyhI.');


INSERT INTO ROLES (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (ROLE_NAME) VALUES ('ROLE_USER');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
