DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS USERS;


CREATE TABLE IF NOT EXISTS BOOKS (
  ID				  INT PRIMARY KEY AUTO_INCREMENT,
  AUTHOR      VARCHAR (50),
  NAME		    VARCHAR(50),
  GENRE_ID		INT
);

CREATE TABLE  IF NOT EXISTS GENRES (
  ID    			INT PRIMARY KEY AUTO_INCREMENT,
  NAME		    VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS USERS (
  ID          INT PRIMARY KEY  AUTO_INCREMENT,
  USER_NAME   VARCHAR(50),
  PASSWORD    VARCHAR(255),
  USER_ROLE   VARCHAR(50)
);

ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE;